version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=todoapp
      - DB_USER=postgres
      - DB_PASSWORD=123456
    depends_on:
      - postgres
    networks:
      - todoapp-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=todoapp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - todoapp-network

networks:
  todoapp-network:
    driver: bridge

volumes:
  postgres-data:
