apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: todoapp
data:
  application-k8s.properties: |
    spring.datasource.url=jdbc:postgresql://postgres:5432/todoapp
    spring.datasource.username=${POSTGRES_USER}
    spring.datasource.password=${POSTGRES_PASSWORD}

    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true

    server.port=8080
