apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secret
  labels:
    app: todoapp
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # postgres (base64 encoded)
  POSTGRES_PASSWORD: MTIzNDU2 # 123456 (base64 encoded)
