apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # postgres (base64 encoded)
  POSTGRES_PASSWORD: MTIzNDU2 # 123456 (base64 encoded)
  POSTGRES_DB: dG9kb2FwcA== # todoapp (base64 encoded)
